#!/bin/sh
set -e
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
ctags --tag-relative=true -R --exclude=@.ctagsignore -f"$dir/$$.tags" --kinds-PHP=dcfit
mv "$dir/$$.tags" "$dir/tags"
